version: '3.4'
services:
    react-nginx-app:
      stdin_open: true
      build:
         context: .
         dockerfile: dockerfile
      ports:
        - 8080:80
      environment:
        - CHOKIDAR_USEPOLLING=true
        - VIRTUAL_HOST=149.129.217.254
        - VIRTUAL_PORT=80
        - LETSENCRYPT_HOST=149.129.217.254
        - LETSENCRYPT_EMAIL=your.email@domain.com
      expose:
        - 80
